title: Kodespråket
tagline: Språket bak koden
description: >- # Ignore newlines
  Hva er språket bak koden? Språket er nemlig det som gir mening og innhold til både oss mennesker og til datamaskiner. Mitt navn er Njord og her på Kodespråket deler jeg mine tanker og meninger om menneske- og datamaskinspråk.
url: https://www.kodespraket.no
locale: nb_NO

author: Njord A. Solberg
email: njosol@pm.me

social:
  name: Njord A. Solberg
  links:
    - https://solbero.github.io/
    - https://github.com/solbero
    - https://no.linkedin.com/in/solbero

remote_theme: brolun/jekyll-theme-monty
plugins:
  - jekyll-feed
  - jekyll-seo-tag
